WITH CTE AS (

    SELECT
    TO_TIMESTAMP(STARTED_AT) STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    
    CASE 
    WHEN dayname(TO_TIMESTAMP(STARTED_AT)) IN ('Sat', 'Sun') 
    THEN  'WEEKEND'
    ELSE 'BUSINESSDAY'
    END
    AS DAY_STARTED_AT,
    CASE 
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5)
    THEN 'SPRING'
     WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUMN'
    END AS SEASON_OF_THE_YEAR

    FROM {{ source('Demo', 'BIKE') }}
    WHERE  STARTED_AT != 'started_at'
)

SELECT * FROM CTE LIMIT 100