WITH CTE AS (

    SELECT
    TO_TIMESTAMP(STARTED_AT) STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    
    {{Date_type('STARTED_AT')}}
    AS DAY_STARTED_AT,
    
    {{get_season('STARTED_AT')}}  AS SEASON_OF_THE_YEAR

    FROM {{ source('Demo', 'BIKE') }}
    WHERE  STARTED_AT != 'started_at'
)

SELECT * FROM CTE LIMIT 100